[build-system]

requires = ["setuptools>=42.0.0",
            "setuptools_scm",
            "wheel",
            "extension-helpers",
            "numpy==1.25.1"]

build-backend = 'setuptools.build_meta'
